name: Build and Deploy
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: learn-java  # Fixed: lowercase to match your folder
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npx ng build --configuration production --base-href /For-Learner/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: learn-java/dist/learn-java # Usually Angular builds into a folder named after the project
          branch: gh-pages
